FROM nginx:1.19.1
ARG NGINX_CONF=""

# 服务器上资源的地址
WORKDIR /data/ops

# 往目录里拷贝打包的文件夹 build，这是最关键的一步
ADD build build

# 这里在docker里执行了nginx配置，这里不使用默认配置
COPY ./scripts/run.sh ./
COPY "${NGINX_CONF}" /etc/nginx/conf.d/default.conf

EXPOSE 80
ENTRYPOINT ["sh", "./run.sh"]